language: csharp
dotnet: none #2.1.402
mono: none #5.10.0

branches:
  only:
  - master

matrix:
  include:
  - os: linux
    env: DOTNETPATH=/home/travis/.dotnet LINUX=1
  - os: osx
    env: DOTNETPATH=/Users/travis/.dotnet

git:
  depth: false

# It is important that we actually install the .NET Core runtime for each that we intend to test.
# Otherwise, the test will run on 2.1 (or whatever is installed on the machine).
# Some failures can be unique to specific versions of the runtime that we claim to support, so we need to test on each.
install:
- export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 DOTNET_CLI_TELEMETRY_OPTOUT=1
- if [ "$LINUX" ]; then sudo apt install libunwind8; fi
- wget https://dot.net/v1/dotnet-install.sh -O /tmp/dotnet-install.sh
- chmod +x /tmp/dotnet-install.sh
- /tmp/dotnet-install.sh -v 2.1.402
- /tmp/dotnet-install.sh -v 2.0.7 --shared-runtime
- export PATH=$DOTNETPATH:$PATH
- dotnet --info

before_script:
  - dotnet restore lib/PuppeteerSharp.sln
  - openssl genrsa -des3 -passout pass:12345 -out testCert.key 1024 -noout
  - openssl req -new -x509 -key testCert.key -out testCert.csr -passin pass:12345 -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com"

script:
- cd lib/PuppeteerSharp.Tests
- DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=0 RuntimeFrameworkVersion=2.1.0  dotnet test -f netcoreapp2.1 -s test.runsettings
